export const dataFooterLogin = [
  "Tiếng Việt",
  "English (UK)",
  "中文(台灣)",
  "한국어",
  "日本語",
  "Français (France)",
  "ภาษาไทย",
  "Ngôn ngữ khác...",
  "Đăng ký",
  "Đăng nhập",
  "Messenger",
  "Facebook Lite",
  "Video",
  "Meta Pay",
  "Cửa hàng trên Meta",
  "Meta Quest",
  "Ray-Ban Meta",
  "Meta AI",
  "Instagram",
  "Threads",
  "Trung tâm thông tin bỏ phiếu",
  "Chính sách quyền riêng tư",
  "Trung tâm quyền riêng tư",
  "Giới thiệu",
  "Tạo quảng cáo",
  "Tạo Trang",
  "Nhà phát triển",
  "Tuyển dụng",
  "Cookie",
  "Lựa chọn quảng cáo",
  "Điều khoản",
  "Trợ giúp",
  "Tải thông tin liên hệ lên & đối tượng không phải người dùng",
  "Meta © 2026",
];
